In [5]:
from PIL import Image
from keras.applications.vgg16 import preprocess_input
import base64
from io import BytesIO
import json
import random
import cv2
from keras.models import load_model
import numpy as np

In [6]:
import tensorflow as tf

In [7]:
from keras.models import load_model

In [9]:
model = load_model('facefeatures_new_model.h5')

In [10]:
import cv2
import numpy as np

In [11]:
#loading the cascades
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

In [12]:
# import face_recognition
def face_extractor(img):
    #function detects faces and returns the cropped face
    #if no face detected, it returns the input image
    #gray = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(img, 1.3, 5)
    if faces is ():
        return None
    
    # #CROP all faces found
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,255,255),2)
        cropped_face = img[y:y+h, x:x+w]
    return cropped_face

   

<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
<>:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
C:\Users\lenovo\AppData\Local\Temp\ipykernel_19836\3651811747.py:7: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if faces is ():


In [18]:
class_labels = ['Shubhankar','Sourav']

#Doing same face recognition with the webcam
#initialize webcam
video_capture = cv2.VideoCapture(0)
# count = 0

while True:
    ret, frame = video_capture.read()
    # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    face = face_extractor(frame)
    
    if type(face) is np.ndarray:
        face = cv2.resize(face, (224, 224))
        im = Image.fromarray(face,'RGB')
        img_array = np.array(im)
        img_array = np.expand_dims(img_array, axis=0)
        pred = model.predict(img_array)
        print(pred)

        name = "None matching"

        pred_class_index = np.argmax(pred[0])

        # get the predicted class label
        name = class_labels[pred_class_index]
        # if(pred[0][1]>0.5):
        #     name = 'Shubhankar'
        # else:
        #     name = 'Unknown'

        cv2.putText(frame,name, (50,50),cv2.FONT_HERSHEY_COMPLEX, 1 ,(0,255,0), 2)
    else:
        cv2.putText(frame, "No face detected", (50,50), cv2.FONT_HERSHEY_COMPLEX, 1 ,(0,0,255), 2)

    cv2.imshow('Video',frame)
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break


video_capture.release()
cv2.destroyAllWindows()




1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 323ms/step
[[4.1338803e-06 9.9999583e-01]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step
[[9.1043030e-06 9.9999094e-01]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 312ms/step
[[1.000000e+00 6.532304e-09]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 337ms/step
[[0.97633934 0.02366071]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 373ms/step
[[9.9999976e-01 2.2091488e-07]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 389ms/step
[[9.9970204e-01 2.9793146e-04]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step
[[9.9999988e-01 1.5469766e-07]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 336ms/step
[[0.98790795 0.01209208]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 389ms/step
[[1.0000000e+00 1.5553799e-10]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 372ms/step
[[0.9816689  0.01833114]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 363ms/step
[[0.9727959  0.02720404]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 343ms/step
[[0.00319207 0.9968079 ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 376ms/step
[[0.28807166 0.71192837]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 369ms/step
[[0.20805901 0.791941  ]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 390ms/step
[[9.9962282

KeyboardInterrupt: 