In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.optimizers import Adam

In [2]:
import numpy as np
from random import randint
from sklearn.preprocessing import MinMaxScaler

In [4]:
train_sample = []
train_label = []

# creating random dataset

for i in range(1000):
    younger_ages = randint(13,64)
    train_sample.append(younger_ages)
    train_label.append(0)

    oder_ages = randint(65,100)
    train_sample.append(oder_ages)
    train_label.append(1)

In [5]:
train_sample = np.array(train_sample)
train_label = np.array(train_label)


In [6]:
train_sample

array([ 34,  77,  31, ...,  95,  38, 100])

In [7]:
train_label

array([0, 1, 0, ..., 1, 0, 1])

In [9]:
scaler = MinMaxScaler(feature_range=(0,1))
scaler_train_sample = scaler.fit_transform(train_sample.reshape(-1,1))

In [10]:
scaler_train_sample

array([[0.24137931],
       [0.73563218],
       [0.20689655],
       ...,
       [0.94252874],
       [0.28735632],
       [1.        ]])

In [11]:
model=Sequential([Dense(16,input_dim=1,activation='relu'),Dense(32,activation='relu'),Dense(2,activation='softmax')])

d:\a27_YEARS_OLD\KERAS\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 16)             │            32 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │           544 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 2)              │            66 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 642 (2.51 KB)

 Trainable params: 642 (2.51 KB)

 Non-trainable params: 0 (0.00 B)

In [20]:
model.compile(Adam(learning_rate=0.001),loss='sparse_categorical_crossentropy',metrics=['accuracy'])

In [22]:
model.fit(train_sample,train_label,batch_size=10,epochs=10)

Epoch 1/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9452 - loss: 0.2198
Epoch 2/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9448 - loss: 0.1838
Epoch 3/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9691 - loss: 0.1463
Epoch 4/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9501 - loss: 0.1482
Epoch 5/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9687 - loss: 0.1148
Epoch 6/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9660 - loss: 0.1123
Epoch 7/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9633 - loss: 0.1023
Epoch 8/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9687 - loss: 0.0933
Epoch 9/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9606 - loss: 0.0987
Epoch 10/10
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.9715 - loss: 0.0833


In [87]:
test_sample = []
test_label = []

# creating random dataset

for i in range(500):
    younger_ages = randint(13,64)
    test_sample.append(younger_ages)
    test_label.append(0)

    oder_ages = randint(65,100)
    test_sample.append(oder_ages)
    test_label.append(1)

In [88]:
test_sample = np.array(test_sample)
test_label = np.array(test_label)

In [89]:
test_sample

array([ 32,  82,  26,  79,  56,  66,  61,  98,  20,  80,  17,  97,  40,
        89,  30,  96,  49,  65,  47,  95,  58,  78,  48, 100,  43,  81,
        40,  65,  45, 100,  54,  70,  58,  65,  42,  99,  60,  91,  42,
        81,  29,  85,  32,  90,  42,  94,  39,  96,  21,  98,  31, 100,
        26,  66,  13,  77,  15,  77,  37,  91,  39,  81,  27,  97,  40,
        95,  33,  78,  20,  77,  59,  81,  62,  85,  31,  73,  62,  85,
        57,  96,  25,  80,  61,  74,  25,  80,  56,  72,  41,  70,  62,
        65,  35,  96,  16,  77,  47,  70,  49,  76,  63,  85,  40,  99,
        61,  83,  33,  68,  36,  85,  57,  95,  20,  80,  33,  74,  43,
        78,  26,  88,  41,  72,  26,  97,  58, 100,  53,  96,  62,  65,
        63,  74,  54,  67,  56,  85,  61,  94,  27,  79,  22,  98,  39,
        83,  63,  79,  44,  79,  38,  83,  31,  71,  50,  68,  57,  96,
        48,  81,  16,  85,  32,  92,  42,  81,  53,  81,  15,  91,  31,
        78,  36,  83,  17,  69,  34,  98,  15,  90,  31,  89,  4

In [90]:
test_label

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,

In [109]:

test_sample_output = model.predict(test_sample,batch_size=10)

100/100 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step


In [110]:
classes_x=np.argmax(test_sample_output,axis=1)

In [111]:
classes_x

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0,

In [105]:
# test_sample_output = test_sample_output.flatten()

In [106]:
# test_sample_output

In [107]:
#extract the predicted class label

# predicted_label = np.where(test_sample_output>0.5,1,0)
# predicted_label

array([[1, 0],
       [0, 1],
       [1, 0],
       ...,
       [0, 1],
       [1, 0],
       [0, 1]])

In [96]:
from sklearn.metrics import confusion_matrix

In [112]:
test_label.shape

(1000,)

In [113]:
classes_x.shape

(1000,)

In [114]:
predicteval = confusion_matrix(test_label,classes_x)

In [115]:
predicteval

array([[486,  14],
       [  0, 500]], dtype=int64)